name:                my-haskell-lambda
version:             0.1.0
github:              "githubuser/my-haskell-lambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/my-haskell-lambda#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 1.1.1
- aeson
- http-types >= 0.12.3

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - my-haskell-lambda

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
