AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: provided
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: ./src
  Entrypoint:
    Type: String
    Default: aws-pod.example.core

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    CodeUri: !Ref CodeUri
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  HLBabashkaLocalRuntime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: HLBabashkaLocalRuntime
      Description: Shared dependencies for stack.
      ContentUri: ./holy-lambda-babashka-runtime
      CompatibleRuntimes:
        - provided

  SharedBabashkaDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedBabashkaDepsLayer
      Description: Shared pods for stack.
      ContentUri: ./.holy-lambda/pods
      CompatibleRuntimes:
        - provided

  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ExampleLambdaFunction
      Handler: aws-pod.example.core.ExampleLambda
      Layers:
        - !Ref SharedBabashkaDepsLayer
        - !Ref HLBabashkaLocalRuntime
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
