version: 2

references:
  polyglot-defaults: &polyglot-defaults
    working_directory: ~/holy-lambda
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    environment:
      JVM_OPTS: -Xmx3200m
      LEIN_ROOT: nbd

  restore-lein-deps: &restore-lein-deps
    restore_cache:
      keys:
        - deps-lein-{{ checksum "project.clj" }}
        - deps-lein-

jobs:
  install-clojure-deps:
    <<: *polyglot-defaults
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - *restore-lein-deps
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: deps-lein-{{ checksum "project.clj" }}

  upload-code-coverage:
     <<: *polyglot-defaults
     steps:
       - checkout
       - *restore-lein-deps
       - run: lein cloverage --codecov
       - run: bash <(curl -s https://codecov.io/bash)

  run-test:
    <<: *polyglot-defaults
    steps:
      - checkout
      - *restore-lein-deps
      - run: lein with-profile eftest eftest

workflows:
  version: 2

  test:
    jobs:
      - install-clojure-deps

      - run-test:
          requires:
            - install-clojure-deps

      - upload-code-coverage:
          requires:
            - run-test
