#!/bin/bash
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

FIERY_NATIVE_VERSION="0.0.4"
DEFAULT_VERSION=fierycod/graalvm-native-image:latest
VERSION=""
VOLUME_PATH=""
CONTAINER_NAME="fnative_$(openssl rand -hex 10)"

printf "$GREEN Version of fnative: $FIERY_NATIVE_VERSION $NC\n"

if [ -z "$1" -a "$1" != " " ]; then
    printf "$RED ERROR: You did not pass any arguments to fnative utility. Exiting... $NC\n"
    exit
fi

if [ -z "$3" -a "$3" != " " ]; then
    printf "$GREEN Using default GraalVM version. Use 3rd parameter to override default version $NC\n"
    VERSION=$DEFAULT_VERSION
else
    VERSION=$3
fi

printf "$GREEN Directory bound: $PWD $NC\n"
printf "$GREEN Name of the container: $CONTAINER_NAME $NC\n"

if [ -z "$2" -a "$2" != " " ]; then
    printf "$GREEN No custom docker settings were passed. You can pass extra settings via 2nd parameter $NC\n\n"
    docker run --name $CONTAINER_NAME -v $PWD:/project:Z -it $VERSION /bin/bash -c "cd /project && $1"
else
    docker run --name $CONTAINER_NAME $2 -v $PWD:/project:Z -it $VERSION /bin/bash -c "cd /project && $1"
fi

printf "$GREEN Successfully compiled project to native $NC\n\n"

printf "$GREEN Removing intermediate container: $CONTAINER_NAME $NC\n\n"

docker rm $CONTAINER_NAME

printf "$GREEN Exiting... $NC\n\n"
