AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 128
  Entrypoint:
    Type: String
    Default: sqs.example.core

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        HL_ENTRYPOINT: !Ref Entrypoint

Resources:
  SubscribeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs.example.core.SubscribeLambda
      Runtime: provided
      CodeUri: .holy-lambda/build/latest.zip
      FunctionName: SubscribeLambdaFunction
      Events:
        ReceiveStringEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ExampleSQS.Arn
            BatchSize: 1
      Environment:
        Variables:
          SQS_URL: !Ref ExampleSQS

  ExampleSQS:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 1
      VisibilityTimeout: 40

  ApiProxyMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs.example.core.ApiProxyMessage
      FunctionName: ApiProxyMessageFunction
      Runtime: provided
      CodeUri: .holy-lambda/build/latest.zip
      Events:
        ProxyMessageEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleHttpApi
            Path: /{message}
            Method: get

      Environment:
        Variables:
          SQS_URL: !Ref ExampleSQS

      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ExampleSQS.QueueName

  ExampleHttpApi:
    Type: AWS::Serverless::HttpApi

Outputs:
  LambdaEndpoint:
    Description: Proxy endpoint for ApiProxyMessageFunction
    Value:
      Fn::Sub: https://${ExampleHttpApi}.execute-api.${AWS::Region}.amazonaws.com
