#!/bin/sh

set -e

export _JAVA_OPTIONS=-Duser.home=/opt/
export BABASHKA_DISABLE_SIGNAL_HANDLERS=true
export XDG_CACHE_HOME=/opt/

/opt/bb -cp "$(cat /opt/classpath)" -m "$(cat BABASHKA_ENTRYPOINT)"
