AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Holy-lambda micro framework babashka compatible runtime/backend layer:
  - Architecture: amd64,
  - Babashka: 0.9.162,
  - SemanticVersion: 0.7.0

Resources:
  BabashkaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: holy-lambda-babashka-runtime-amd64
      Description: holy-lambda micro framework babashka compatible backend layer for amd64.
      ContentUri: ./holy-lambda-babashka-runtime-amd64.zip
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - provided
        - provided.al2
      LicenseInfo: https://github.com/FieryCod/holy-lambda/tree/master/modules/holy-lambda-babashka-layer/LICENSE
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref BabashkaLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: holy-lambda-babashka-runtime-amd64
    Author: Karol Wojcik
    HomePageUrl: https://github.com/FieryCod/holy-lambda
    Labels: ['holy-lambda', 'layer', 'babashka', 'lambda', 'clojure']
    SpdxLicenseId: MIT
    Description: >
      Holy-lambda micro framework babashka compatible runtime/backend layer:
      - Architecture: amd64,
      - Babashka: 0.9.162,
      - SemanticVersion: 0.7.0
    LicenseUrl: LICENSE
    ReadmeUrl: README-amd64.md
    SourceCodeUrl: https://github.com/FieryCod/holy-lambda/tree/master/modules/holy-lambda-babashka-layer
