# https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.3.0-dev-20210910_2147/graalvm-ce-java8-linux-amd64-dev.tar.gz
# New versions
# https://github.com/graalvm/graalvm-ce-dev-builds/releases/
FROM oraclelinux:8-slim
MAINTAINER Karol Wójcik <Karol Wójcik>

# Based on https://github.com/graalvm/container/blob/master/community/Dockerfile.ol8
RUN microdnf update -y oraclelinux-release-el8 \
    && microdnf --enablerepo ol8_codeready_builder install bzip2-devel ed gcc gcc-c++ gcc-gfortran gzip file fontconfig less libcurl-devel make openssl openssl-devel readline-devel tar unzip zip \
    vi which xz-devel zlib-devel findutils glibc-static libstdc++ libstdc++-devel libstdc++-static zlib-static wget \
    && microdnf clean all
RUN fc-cache -f -v

ENV CLJ_CACHE=/project/.holy-lambda/clojure
ENV CLJ_COFIG=/project/.holy-lambda/clojure
ENV CLOJURE_TOOLS_DIR=/project/.holy-lambda
ENV HOME=/project/.holy-lambda
ENV XDG_CACHE_HOME=/project/.holy-lambda
ENV XDG_CONFIG_HOME=/project/.holy-lambda
ENV XDG_DATA_HOME=/project/.holy-lambda
ENV GITLIBS=/project/.holy-lambda/.gitlibs/
ENV LANG=en_US.UTF-8 
ENV JAVA_HOME=/opt/graalvm-dev

# --------------- UPDATE ------------------
# -----------------------------------------
ARG BABASHKA_VERSION=0.6.1
ARG GRAALVM_JAVA_URL={{java-version-url}}
ARG GRAALVM_NATIVE_IMAGE_URL={{native-image-url}}
ARG GRAALVM_JAVA_CORD=graalvm-ce-linux.tar.gz
ARG GRAALVM_NATIVE_IMAGE_CORD=native-image.jar
# -----------------------------------------

RUN curl https://raw.githubusercontent.com/graalvm/container/master/community/gu-wrapper.sh > gu-wrapper.sh
RUN mv gu-wrapper.sh /usr/local/bin/gu

RUN curl -L $GRAALVM_JAVA_URL > $GRAALVM_JAVA_CORD
RUN curl -L $GRAALVM_NATIVE_IMAGE_URL > $GRAALVM_NATIVE_IMAGE_CORD

RUN set -eux && gunzip -dc $GRAALVM_JAVA_CORD | tar x -C /opt/ \
    # Set alternative links
    && mkdir -p "/usr/java" \
    && ln -sfT "$JAVA_HOME" /usr/java/default \
    && ln -sfT "$JAVA_HOME" /usr/java/latest \
    && for bin in "$JAVA_HOME/bin/"*; do \
    base="$(basename "$bin")"; \
    [ ! -e "/usr/bin/$base" ]; \
    alternatives --install "/usr/bin/$base" "$base" "$bin" 20000; \
    done \
    && chmod +x /usr/local/bin/gu

# Install native-image
RUN gu -L install $GRAALVM_NATIVE_IMAGE_CORD

# Cleanup
RUN rm -Rf $GRAALVM_JAVA_CORD $GRAALVM_NATIVE_IMAGE_CORD

# Provide download_pods command
COPY download_pods download_pods.clj /
RUN chmod +x download_pods && mv download_pods /bin/download_pods

# Install babashka
RUN wget -c https://github.com/babashka/babashka/releases/download/v$BABASHKA_VERSION/babashka-$BABASHKA_VERSION-linux-amd64.tar.gz -O - | tar -xz \
    && chmod +x bb \
    && mv bb /bin/bb

WORKDIR /project
