AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: provided
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 128
  Entrypoint:
    Type: String
    Default: com.company.example-lambda.core

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ExampleLambdaFunction
      Handler: com.company.example-lambda.core.ExampleLambda
      # For docker based deployments use:
      # PackageType: Image
      # and remove Runtime parameter
      CodeUri: src
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /
            Method: GET
      Layers:
        - arn:aws:lambda:eu-central-1:443526418261:layer:holy-lambda-babashka-runtime:47
    # For docker based deployments
    # Metadata:
    #   Dockerfile: Dockerfile
    #   DockerContext: .
    #   DockerTag: v1

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: Prod

Outputs:
  ExampleLambdaEndpoint:
    Description: Endpoint for ExampleLambdaFunction
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
