AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: java8
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  HelloLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.HelloLambda
      CodeUri: target/output.jar
      FunctionName: HelloLambdaFunction
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  RedirectLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.RedirectLambda
      CodeUri: target/output.jar
      FunctionName: RedirectLambdaFunction
      Events:
        EmptyEvent:
          Type: Api
          Properties:
            Path: /redirect
            Method: get

  AsyncLambdaPromiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.AsyncLambdaPromise
      CodeUri: target/output.jar
      FunctionName: AsyncLambdaPromiseFunction
      Events:
        EmptyEvent:
          Type: Api
          Properties:
            Path: /async-promise
            Method: get

  AsyncLambdaFutureFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.AsyncLambdaFuture
      CodeUri: target/output.jar
      FunctionName: AsyncLambdaFutureFunction
      Events:
        EmptyEvent:
          Type: Api
          Properties:
            Path: /async-future
            Method: get

  AsyncLambdaChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.AsyncLambdaChannel
      CodeUri: target/output.jar
      FunctionName: AsyncLambdaChannelFunction
      Events:
        EmptyEvent:
          Type: Api
          Properties:
            Path: /async-channel
            Method: get

  ByeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-lambda.core.ByeLambda
      CodeUri: target/output.jar
      FunctionName: ByeLambdaFunction
      Events:
        ByeEvent:
          Type: Api
          Properties:
            Path: /bye
            Method: get
