AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Example basic lambda using `holy-lambda` micro library

  '
Parameters:
  Runtime:
    Type: String
    Default: provided
  Timeout:
    Type: Number
    Default: 25
  MemorySize:
    Type: Number
    Default: 2000
Globals:
  Function:
    Runtime:
      Ref: Runtime
    Timeout:
      Ref: Timeout
    MemorySize:
      Ref: MemorySize
Resources:
  ExampleSQS:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 1
  ApiProxyMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs-example.core.ApiProxyMessage
      CodeUri: s3://holy-lambda--sqs-example-fierycod/sqs-example/e98ad29ffad728cafcd0ce536a122964
      FunctionName: ApiProxyMessageFunction
      Events:
        ProxyMessageEvent:
          Type: Api
          Properties:
            Path: /{message}
            Method: get
      Environment:
        Variables:
          SQS_URL:
            Ref: ExampleSQS
      Policies:
      - SQSSendMessagePolicy:
          QueueName:
            Fn::GetAtt:
            - ExampleSQS
            - QueueName
  SubscribeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs-example.core.SubscribeLambda
      CodeUri: s3://holy-lambda--sqs-example-fierycod/sqs-example/e98ad29ffad728cafcd0ce536a122964
      Events:
        ReceiveStringEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - ExampleSQS
              - Arn
            BatchSize: 1
      Environment:
        Variables:
          SQS_URL:
            Ref: ExampleSQS
