AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: <HOLY_LAMBDA_RUNTIME>
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: <HOLY_LAMBDA_CODE_URI>
  Entrypoint:
    Type: String
    Default: <HOLY_LAMBDA_ENTRYPOINT>

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    CodeUri: !Ref CodeUri
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ExampleLambdaFunction
      Handler: basic.example.core.ExampleLambda
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
