AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: <HOLY_LAMBDA_RUNTIME>
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: <HOLY_LAMBDA_CODE_URI>
  Entrypoint:
    Type: String
    Default: <HOLY_LAMBDA_ENTRYPOINT>

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    CodeUri: !Ref CodeUri
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.core.ExampleLambda
      Layers:
        - !Ref SharedClojureBabashkaDepsLayer
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /
            Method: GET

  SharedClojureBabashkaDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedClojureBabashkaDepsLayer
      Description: Shared dependencies for stack.
      ContentUri: ./holy-lambda-babashka-runtime
      CompatibleRuntimes:
        - provided

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: Prod

Outputs:
  TestEndpoint:
    Description: Test endpoint
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
