AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 128
  Entrypoint:
    Type: String
    Default: <HOLY_LAMBDA_ENTRYPOINT>

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  BabashkaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: holy-lambda-babashka-runtime
      Description: holy-lambda micro framework babashka compatible runtime layer
      ContentUri: ./holy-lambda-babashka-runtime

  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      # PackageType: Image
      Runtime: provided
      Handler: example.core.ExampleLambda
      CodeUri: ./.holy-lambda/build/latest.zip
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /
            Method: GET
    # Metadata:
    #   DockerTag: new-tag
    #   DockerContext: .
    #   Dockerfile: Dockerfile

  ExampleLambdaFunctionv2:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Handler: example.core.ExampleLambdav2
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /example
            Method: GET

    Metadata:
      DockerTag: new-tag
      DockerContext: .
      Dockerfile: Dockerfile

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: Prod

Outputs:
  TestEndpoint:
    Description: Test endpoint
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
