name: Holy Lambda Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.1

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.6.1

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}

      - name: Test the core
        run: lein with-profile eftest eftest

      - name: Login to Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u FieryCod --password-stdin

      - name: Build all images
        run: |
          cd docker && bb registry.clj
