AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: <HOLY_LAMBDA_RUNTIME>
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: <HOLY_LAMBDA_CODE_URI>
  Entrypoint:
    Type: String
    Default: <HOLY_LAMBDA_ENTRYPOINT>

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    CodeUri: !Ref CodeUri
    Environment:
      Variables:
        Entrypoint: !Ref Entrypoint

Resources:
  ExampleSQS:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 1
      VisibilityTimeout: 40

  ApiProxyMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs.example.core.ApiProxyMessage
      FunctionName: ApiProxyMessageFunction
      Events:
        ProxyMessageEvent:
          Type: Api
          Properties:
            Path: /{message}
            Method: get

      Environment:
        Variables:
          SQS_URL: !Ref ExampleSQS

      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ExampleSQS.QueueName

  SubscribeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqs.example.core.SubscribeLambda
      FunctionName: SubscribeLambdaFunction
      Events:
        ReceiveStringEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ExampleSQS.Arn
            BatchSize: 1
      Environment:
        Variables:
          SQS_URL: !Ref ExampleSQS
